version: 0.2

env:
  variables:
    SDLC_ENVIRONMENT: "$1"
    # GIT_REPO: "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/dockerecrtestbuild"
  parameter-store:
    GIT_USER: git-username
    GIT_PASS: git-password
phases:
  install:
    commands:
      - apt-get update -y && apt-get install -y git
  pre_build:
    commands:
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_VERSION
      - |
        REPO_NAME=$(echo "$CODEBUILD_SOURCE_REPO_URL" | awk -F "/" '{print $NF}')
        BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | awk -F "/" '{print $NF}')
        echo "SDLC_ENVIRONMENT is : $SDLC_ENVIRONMENT"
        echo "BRANCH_NAME is : $BRANCH_NAME"
        echo "CODEBUILD_SOURCE_REPO_URL is : $CODEBUILD_SOURCE_REPO_URL"
        echo "CODEBUILD_SOURCE_VERSION is : $CODEBUILD_SOURCE_VERSION"
        # cat <<EOF
        #   SDLC_ENVIRONMENT=$SDLC_ENVIRONMENT
        #   BRANCH_NAME=$BRANCH_NAME
        # EOF
      - echo "Inside pre_build section1"
      - echo "machine git-codecommit.us-east-1.amazonaws.com" >> ~/.netrc
      - echo "login $GIT_USER" >> ~/.netrc
      - echo "password $GIT_PASS" >> ~/.netrc
      - git clone -b $BRANCH_NAME $CODEBUILD_SOURCE_REPO_URL
  build:
    commands:
      - echo "inside build commands and printing all environment variables below"
      - printenv
      - echo `pwd`
      - echo "This is the commit id from Source Control - $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "This is Codecommit Repo URL - $CODEBUILD_SOURCE_REPO_URL"
      - echo "This is Codecommit Repo Name - $REPO_NAME"
      - echo "This is the CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
      - bash $CODEBUILD_SRC_DIR/scripts/utility-script.sh $SDLC_ENVIRONMENT $REPO_NAME